In [8]:
import numpy as np
print(np.__version__)



1.20.3


In [7]:
import pandas as pd
print(pd.__version__)

1.3.2


In [4]:
import urllib.request
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = 'data.csv'
urllib.request.urlretrieve(url,filename)

('data.csv', <http.client.HTTPMessage at 0x13e55738f10>)

###  1 Average price of BMW cars

In [ ]:
df=pd.read_csv('data.csv')

In [38]:
df


Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [16]:

average_price_BMW_cars=df.MSRP.mean()
print(f"Average price of BMW cars is $ {round(average_price_BMW_cars,4)}.")

Average price of BMW cars is $ 40594.737.


In [33]:
after_year=df[df["Year"]>=2015].sort_values("Year")
missing_hp=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].isna().sum()

In [37]:
mean_hp_before=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].mean()

after_year['Engine HP']=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].fillna(mean_hp_before)
mean_hp_after=after_year['Engine HP'].mean()
print(round(mean_hp_before))
print(round(mean_hp_after))

273
273


In [50]:
rolls_royce=df.loc[(df["Make"]=="Rolls-Royce"),["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
rolls_royce.np.array()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [91]:
x=np.array(rolls_royce)
x.astype(int)

array([[325,   8,  15],
       [563,  12,  19],
       [563,  12,  21],
       [563,  12,  20],
       [322,  12,  15],
       [453,  12,  19],
       [624,  12,  21]])

In [104]:
t=x.T
XTX=np.matmul(t,x).astype(int)
XTX

array([[1754801,   39656,   65196],
       [  39656,     928,    1500],
       [  65196,    1500,    2454]])

In [111]:
inverse_xtx=np.linalg.inv(XTX)
inverse_xtx


array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [112]:
inverse_xtx.sum()


0.032212320677486195

In [117]:
y=[1000, 1100, 900, 1200, 1000, 850, 1300]
w=np.matmul(np.matmul(inverse_xtx,t),y)
w[0]

0.19989598183186175