In [8]:
import numpy as np
print(np.__version__)



1.20.3


In [7]:
import pandas as pd
print(pd.__version__)

1.3.2


In [4]:
import urllib.request
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = 'data.csv'
urllib.request.urlretrieve(url,filename)

('data.csv', <http.client.HTTPMessage at 0x13e55738f10>)

###  1 Average price of BMW cars

In [ ]:
df=pd.read_csv('data.csv')

In [ ]:
df


In [16]:

average_price_BMW_cars=df.MSRP.mean()
print(f"Average price of BMW cars is $ {round(average_price_BMW_cars,4)}.")

Average price of BMW cars is $ 40594.737.


In [33]:
after_year=df[df["Year"]>=2015].sort_values("Year")
missing_hp=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].isna().sum()

In [37]:
mean_hp_before=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].mean()

after_year['Engine HP']=df[df["Year"]>=2015].sort_values("Year")['Engine HP'].fillna(mean_hp_before)
mean_hp_after=after_year['Engine HP'].mean()
print(round(mean_hp_before))
print(round(mean_hp_after))

273
273


In [50]:
rolls_royce=df.loc[(df["Make"]=="Rolls-Royce"),["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
rolls_royce.np.array()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [91]:
x=np.array(rolls_royce)
x.astype(int)

array([[325,   8,  15],
       [563,  12,  19],
       [563,  12,  21],
       [563,  12,  20],
       [322,  12,  15],
       [453,  12,  19],
       [624,  12,  21]])

In [104]:
t=x.T
XTX=np.matmul(t,x).astype(int)
XTX

array([[1754801,   39656,   65196],
       [  39656,     928,    1500],
       [  65196,    1500,    2454]])

In [111]:
inverse_xtx=np.linalg.inv(XTX)
inverse_xtx


array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [112]:
inverse_xtx.sum()


0.032212320677486195

In [117]:
y=[1000, 1100, 900, 1200, 1000, 850, 1300]
w=np.matmul(np.matmul(inverse_xtx,t),y)
w[0]

0.19989598183186175